### PR TITLE
Galal Student Bio 

### PR DESCRIPTION
**Pull request by galalkoro98**
### General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work
- [ ] any embedded code snippets are formatted

- [x] I wrote my markdown locally on a new branch
- [x] My bio file is named _exactly_ the same as my GitHub username
- [x] My `bio` link in the class README opens to my student bio file
- [x] I pulled and merged `main` into my branch before pushing
- [x] I pushed my branch to the class repository and opened a PR
- [x] I went through the PR checklist
- [x] All the CI check pass
- [x] I assigned a coach to review my PR
      [linked my PR to this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

### CODE REVIEW

**Comment by talmurshidi** [comment]
Well done @galalkoro98 
Please check the required checklist in the Pull Request and in the issue that you have created.

**Comment by yildiztugba** [comment]
Hi @galalkoro98  please check if you finished the checklist in pr and your deliverable issue. You have some missing parts, For example:

- PR has a descriptive title
- is linked to an issue (if it is related)
- ….

When you check all of them, please move your pull request to the project board(READY FOR REVIEW.)

**Comment by galalkoro98** [comment]
fixed

**Review by yildiztugba — APPROVED** [review]
well done

**Pull request merged**
