### PR TITLE
Ghasem :student-bio

### PR DESCRIPTION
**Pull request by QasemMousavi**
# Student Bio PR

Write a short bio for yourself using Markdown and add it to your class
repository using Local/Remote workflows. Just a little intro so your classmates
can get to know you.

### General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [x] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work
- [x] any embedded code snippets are formatted

### CODE REVIEW

**Comment by yildiztugba** [comment]
hi @QasemMousavi your md file is empty. you need to write a short bio for yourself. You can use [markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to add headers, links, images, tables etc. Also you can add emojies from [here](https://gist.github.com/rxaviers/7360908).  after writing your md file and doing format check,you can push to the same branch. Your pull request will update your changes automatically.

**Comment by bermarte** [comment]
Hi, you should practice markdown, while you have added just a title, which is not enough. Maybe this can help you? https://www.youtube.com/watch?v=HUBNt18RFbo

**Comment by QasemMousavi** [comment]
Thank you I will watching the video 🙏

**Review by yildiztugba — APPROVED** [review]
nice bio 👍

**Pull request merged**
