### PR TITLE
filmon-goitom: workflow , student-bio

### PR DESCRIPTION
**Pull request by filmon-goitom**
### General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [x] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work
- [x] any embedded code snippets are formatted

### CODE REVIEW

**Comment by bermarte** [comment]
Reviewers are usually coaches. You should thick the checkboxes if you did the tasks, otherwise you leave them unchecked.
See https://stackoverflow.com/questions/47344571/how-to-draw-checkbox-or-tick-mark-in-github-markdown-table

**Comment by filmon-goitom** [comment]
could someone look on my pull request. i couldn't find the error.

**Comment by bermarte** [comment]
> could someone look on my pull request. i couldn't find the error.

Your .md file is empty.

**Review by bermarte — CHANGES_REQUESTED** [review]
You should write your bio here

**Comment by filmon-goitom** [comment]
I need help with: some errors on lint:ls 
What went well? 
creating bio using .md file , using all emojis and  formatting them.

What went wrong?
i put wrong the name of  my bio file while i was pushing.

Sunday preparation work
doing

**Comment by talmurshidi** [comment]
Hey @filmon-goitom 
If you have time now, I can follow up with you using ZOOM.

**Comment by yildiztugba** [comment]
@filmon-goitom you have a nice student bio, without error. Could you please go through the checklist, after checked all, please move your pull request to READY FOR REVIEW column (it is on the right side, insede the projects/deliverables). Make sure you linked pr to your issue (it is also right side, click development, find your issue)

**Comment by bermarte** [comment]
Good job. You are almost done, there are only 2 steps to do, then it will be merged.

**Review by bermarte — APPROVED** [review]

**Pull request merged**
