### PR TITLE
John Edelbi - workflow - add johnedelbi bio to student-bios folder

### PR DESCRIPTION
**Pull request by johnedelbi**
### General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work
- [x] any embedded code snippets are formatted

### CODE REVIEW

**Comment by yildiztugba** [comment]
if you finish your pr, please move it to the project board (READY FOR REVIEW column):wink: I noticed that your file name doesn't match with your github username thats why i don't see your linked bio on the home page. other thing is  your title of pr need a descriptive name.

**Comment by bermarte** [comment]
Well done. Minor remark: your username is all lowercase.

**Review by bermarte — APPROVED** [review]

**Comment by bermarte** [comment]
> if you finish your pr, please move it to the project board (READY FOR REVIEW column)😉 I noticed that your file name doesn't match with your github username thats why i don't see your linked bio on the home page. other thing is your title of pr need a descriptive name.

Remember to move your issue in the column READY FOR REVIEW and change the file name to `johnedelbi.md,  after that we can merge it.

**Comment by yildiztugba** [comment]
@johnedelbi you might missed last comment from bermarte. Please move your project to READY FOR REVIEW. then we can merge it

**Comment by johnedelbi** [comment]
no no @yildiztugba i didn't missed it but i try to fix the problem since yesterday 

i try a lot to change the file name from JohnEdelbi to johnedelbi and push but as i see on the repo it still the same

**Comment by johnedelbi** [comment]
so i will change it to ready to review when i fix that today

**Comment by johnedelbi** [comment]
image

**Comment by johnedelbi** [comment]
it's ready to review now sorry but finally i use github to change the file name cuz i can't manage to know how to fix it from vs code

**Review by yildiztugba — APPROVED** [review]
You did very good job and solved your problem. Also you have a nice bio. ready to go!!

**Pull request merged**
